version: '3.9'

services:
  backend:
    build: ./backend
    container_name: peliculas_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_DBNAME: ${MONGO_DBNAME}


  frontend:
    build: ./frontend
    container_name: peliculas_frontend
    restart: always
    ports:
      - "8080:80"
